### PR TITLE
Benchmark against pytomlpp and tomli

### PR DESCRIPTION
**Pull request by hukkinj1**
Added pytomlpp and Tomli to the benchmark. I re-ran the benchmark in a clean venv, using CPython 3.8.5 on a `Intel i5-8350U CPU @ 1.70GHz` cpu.

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Looks good, I'll run myself when I'm back at my computer, then merge.

**Comment by samuelcolvin** [comment]
Thanks so much, this is great.

Now you've made me spend half a day trying to make rtoml faster by removing `parse_datetime` needing to be implemented in python. :smile: :angry:

**Comment by hukkinj1** [comment]
Haha, is the goal to beat the C++ implementation? :smile:

**Comment by samuelcolvin** [comment]
hard not to try when the difference is so small.

**Comment by samuelcolvin** [comment]
see #25, rtoml is now around 8% faster than pytomlpp.

I'll wait to update the benchmarks until I've release a new version an can use the manylinux binary for the benchmark which is fairer.

**Comment by hukkinj1** [comment]
Awesome congrats! Now waiting for pytomlpp to make their next move, haha

**Comment by samuelcolvin** [comment]
v0.7 released and benchmarks updated.

**Comment by hukkin** [comment]
Booo, for making us others look bad. :smile: 

Btw I was toying around with different sorts of data a few days ago and discovered that `rtoml` performance suffers quite a lot with IIRC slightly larger TOML files (around 1000 lines).

I think the data I used was generated with something like
```python
import uuid
for _ in range(500): 
    print(f"[{uuid.uuid4()}.a.b]") 
    print("key='val'")
```

**Comment by samuelcolvin** [comment]
Interesting I think the problem could be at:

https://github.com/samuelcolvin/rtoml/blob/ccd2c01a210bcd3b7cf0be8dbbdedab352476e32/src/lib.rs#L23

Really it would be better to create an object at the right size initially rather than dynamically change its size.

I'll try and see if there's a way to fix this with pyo3.

**Pull request merged**
