### PR TITLE
build wheels for ppc64le and s390x

### LINKED ISSUE #44: Feature Request: Add support for s390x
Building wheel for rtoml (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-s390x-cpython-310
      creating build/lib.linux-s390x-cpython-310/rtoml
      copying rtoml/__init__.py -> build/lib.linux-s390x-cpython-310/rtoml
      copying rtoml/py.typed -> build/lib.linux-s390x-cpython-310/rtoml
      running build_ext
      running build_rust
      error: can't find Rust compiler

Could you add support for s390x?

### PR DESCRIPTION
**Pull request by messense**
Closes #44

### CODE REVIEW

**Comment by messense** [comment]
Test runs:

* ppc64le: https://github.com/samuelcolvin/rtoml/actions/runs/3455117590/jobs/5766900045
* s390x: https://github.com/samuelcolvin/rtoml/actions/runs/3455117590/jobs/5766900069

**Comment by samuelcolvin** [comment]
I've added the label to prompt building binaries, can you push again?

**Comment by samuelcolvin** [comment]
Also, would you like me to make you a collaborator on this and watchfiles to speed things up?

**Comment by samuelcolvin** [comment]
Thanks so much for fixing this btw.

**Comment by messense** [comment]
> Also, would you like me to make you a collaborator on this and watchfiles to speed things up?

ok.

**Comment by samuelcolvin** [comment]
Invited, thanks so much for this.

**Pull request merged**
