### PR TITLE
Testing joerick/cibuildwheel#194

### PR DESCRIPTION
**Pull request by YannickJadoul**
Cfr. discussion in joerick/cibuildwheel#194

### CODE REVIEW

**Comment by YannickJadoul** [comment]
(This is not the fix, yet, btw; but I'd like to see if this still fails, to know if the next commit is indeed the one that fixes things.)

**Comment by samuelcolvin** [comment]
Okay, good luck.

**Comment by YannickJadoul** [comment]
CI didn't get triggered, though?

**Comment by samuelcolvin** [comment]
My mistake, problem is `on: [push]`.

You can just add `pull_request` to the list or I'll look tomorrow.

**Comment by YannickJadoul** [comment]
Still failing, but failing during the link phase, now; and not anymore because of the assert of `pip.exe`, so @mayeut's hunch about the Windows `PATH`-separator was correct.

Any further hunch on what's going on with the linker error, @samuelcolvin?

**Comment by samuelcolvin** [comment]
no idea i'm afraid, bit it passed in #9 so much be a change in `cibuildwheel`

**Comment by YannickJadoul** [comment]
Yes, I had noticed. But, to be fair, all you've done is not run `get-pip.py` and that following assert, so I don't know why there would be a difference?
https://github.com/samuelcolvin/cibuildwheel/compare/a8d5565feeeb657fa9d8fccf9ad72868e26facf1...github-actions

**Comment by YannickJadoul** [comment]
Oh, wait, I think I do know what's going on:

Before, the wrong separator broke `PATH`, and the newly installed Python couldn't be found, so the preinstalled Python is used. Now that the `PATH` works, something else is going wrong, later.

**Comment by YannickJadoul** [comment]
There you go; not a problem with cibuildwheel or @mayeut's PR of the GitHub actions. Explanation:

1. Original error: your `PATH` separator was wrong; on Window, it's `;` instead of `:` (as @mayeut suggested)
2. `HOME` doesn't exist as environment variable on Windows; it's `UserProfile` (but I'm actually not even sure you need to set it; things failed in exactly the wrong way if you don't set it, so I'll still try with `CIBW_ENVIRONMENT_WINDOWS=''`; maybe GitHub Actions already adds it to your `PATH`)
3. Since `cibuildwheel` tries to build both a 32-bit and 64-bit wheel, and your Rust toolchain installed is 64-bit, the 32-bit build (which comes first) fails. Skipping it results in a successful build. The reason it didn't fail on `main` is because the wrong `PATH` separator messes up the `PATH` and so the 32-bit  Python that `cibuildwheel` installs is not used. I'm not a Rust user, though, so I don't understand how you'd build 32-bit wheels; but it's definitely not `cibuildwheel`.
4. PS: I don't really understand why you do the `CIBW_BUILD: ${{ matrix.target }}`? One of the main points of `cibuildwheel` is to have all wheels built with a single command, without worrying too much, so I'd think that just one job running `cibuildwheel` would be cleaner? Otherwise, you could just as well run `pip wheel` yourself.

**Comment by samuelcolvin** [comment]
Thank so much for looking into this, I'll fix or work around the rust issue.

---

> PS: I don't really understand why you do the `CIBW_BUILD: ${{ matrix.target }}`

I wasn't sure exactly how `cibuildwheel` works on windows and macos, I was just trying to be as correct as possible.

> without worrying too much, so I'd think that just one job running cibuildwheel would be cleaner

Well doing separate builds for python 3.7 and 3.8 makes it much faster, particularly for linux, so I might as well keep that.

**Comment by samuelcolvin** [comment]
I'll use this until joerick/cibuildwheel#194 gets merged.

**Comment by samuelcolvin** [comment]
For anyone coming to this interested in the rust side of things; I got 32bit windows binaries to work too on #10, though it required some hacking.

**Pull request merged**
