### PR TITLE
Test against, officially support Python 3.11

### PR DESCRIPTION
**Pull request by homeworkprod**

### CODE REVIEW

**Comment by homeworkprod** [comment]
`cargo clippy` raises errors, but that's also the case on `main`.

Tried a few of its suggestions but they did not fix the issue for me.

**Comment by homeworkprod** [comment]
Cool, thanks!

> but unfortunately you've blocked me from contributing to your PR.

Not sure where I could've influenced that for this PR, but I'll keep an extra eye open in the future.

**Comment by samuelcolvin** [comment]
> Not sure where I could've influenced that for this PR, but I'll keep an extra eye open in the future.

When you create a PR, there's an option to "Allow edits...", this must be check for me to be able to push to your PR.

image

**Comment by homeworkprod** [comment]
That's strange. I have seen this option before, but I did not encounter it with this PR, and I just attempted to create another one (from my fork to the source repo) which also doesn't give me that option (including switching between draft and non-draft):

github-pr-no-option-to-allow-edits

**Comment by samuelcolvin** [comment]
Oh, perhaps it's because the pr is in draft?

**Comment by homeworkprod** [comment]
What I was trying to say was that I flipped between draft and non-draft using the dropdown functionality of the big green button and it did not result in that checkbox being shown in either state.

Maybe it's only shown when using a different path to create a PR, or there is some user default setting I did not unearth yet, but so far I could not find a way to allow PR edits by maintainers.

Not sure why this is, but it's probably worth keeping in mind that a user might not have the chance to make that decision.

**Comment by samuelcolvin** [comment]
Interesting, I often edit PRs of contributors. It's extremely rare (I guess <5% of the time) that I can't push to a PR.

**Comment by homeworkprod** [comment]
For the record, for anyone coming across this:

The issue is because my fork is in an organization and GitHub does not allow maintainers to push there.

See: https://github.com/orgs/community/discussions/5634

**Pull request closed without merging**
