### PR TITLE
Build Python 3.10 wheels

### PR DESCRIPTION
**Pull request by stranger-danger-zamu**
I'm pretty sure this covers all the changes necessary for building py3.10 wheels.

### CODE REVIEW

**Comment by samuelcolvin** [comment]
also here:

https://github.com/samuelcolvin/rtoml/blob/a9ac7709c4bd288a1685cca64cd7752152f15d38/setup.py#L41

**Comment by samuelcolvin** [comment]
not quite as simple as we throught, but now it's working.

**Comment by samuelcolvin** [comment]
thanks a lot.

**Comment by stranger-danger-zamu** [comment]
Ah just saw this! Thanks the quick turn around. I've been having to compile the wheels for a week before I realized I probably just open an issue.

**Pull request merged**
