### PR TITLE
Support serialization to "pretty" output

### PR DESCRIPTION
**Pull request by homeworkprod**
Hi Samuel, thanks for the nice library!

I found myself interested in "pretty" output because line-wrapped arrays make for more compact diffs of TOML under version control.

In the suggested implementation I have opted for a keyword argument in the Python layer to enable the new behavior on demand, but went with a separate function (unfortunately with a bit of code duplication) in Rust due to its lack of optional, default, and/or named arguments (as of mid-2020).

Note regarding the test cases: According to the [documentation of `toml::ser::Serializer::pretty_string`](https://docs.rs/toml/0.5.6/toml/ser/struct.Serializer.html#method.pretty_string), the "pretty" output for `text = "\nfoo\nbar\n"` should be
```toml
text = '''
foo
bar
'''
```
but I found it to be this instead (notice the blank line after the opening triple quotes):
```toml
text = '''

foo
bar
'''
```

Please let me know what you think and have a nice weekend!

### CODE REVIEW

**Comment by homeworkprod** [comment]
Unfortunately, the CI build steps fail because of #12.

**Comment by samuelcolvin** [comment]
this looks great. Please rebase to fix the errors and update the readme.

**Comment by homeworkprod** [comment]
Done. Is this what you had in mind regarding the README?

**Comment by samuelcolvin** [comment]
great. I guess I'l release a new version. Is there anything you need?

**Comment by homeworkprod** [comment]
Excellent!

I don't think I need anything else.

**Comment by samuelcolvin** [comment]
deploying now.

**Comment by homeworkprod** [comment]
Thanks a lot. Works as expected!

**Pull request merged**
