### PR TITLE
Add pyproject.toml

### PR DESCRIPTION
**Pull request by oittaa**
Without "setuptools-rust" the installation fails on MacOS computers with M1 CPUs.

https://github.com/PyO3/setuptools-rust#pyprojecttoml

Fixes https://github.com/hukkin/tomli/issues/147

### CODE REVIEW

**Comment by samuelcolvin** [comment]
I'd strongly prefer not to add `pyproject.toml` unless absolutely necessary.

Can this be accomplished with `install_requires` in `setup.py`?

**Comment by oittaa** [comment]
You're importing from `setuptools-rust` in https://github.com/samuelcolvin/rtoml/blob/69cfb6f8b3fb319a6534fb2d64320a9a5128231b/setup.py#L5 and that will fail even if you later in the file use `setup(install_requires=["setuptools", "wheel", "setuptools-rust"], ...)`

**Comment by samuelcolvin** [comment]
What about [`setup.cfg`](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html) then?

Alternatively you could try catching `ImportError` in `setup.py`, but you'll need to test and see what works.

**Comment by oittaa** [comment]
> What about [`setup.cfg`](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html) then?

The same issue, it doesn't help if there are things in setup.py that depend on the requirements.

> Alternatively you could try catching `ImportError` in `setup.py`, but you'll need to test and see what works.

I don't really know what you mean by this. If the import fails, manually cloning the repo from https://github.com/PyO3/setuptools-rust and installing it somehow?

[PEP518](https://www.python.org/dev/peps/pep-0518/) is pretty clear how to handle the build system dependencies.

**Comment by samuelcolvin** [comment]
Okay, I've looked and you're right, `pyproject.toml` seems to be the only way to do this.

However I really don't want more configure files than are necessary. I'm therefore happy to accept this if we switch completely from `setup.cfg` to `pyproject.toml`.

All tools configured via `setup.cfg` can also be configured via `pyproject.toml`, except flake8 which will have to be configured via command line arguments in `Makefile`.

Are you happy to do this? Otherwise I'll do it when I next get around to it.

**Comment by samuelcolvin** [comment]
should also be fixed by #34.

Can you confirm whether binaries like `rtoml-0.7.1-cp39-cp39-macosx_11_0_arm64.whl` will work for you?

**Comment by oittaa** [comment]
> should also be fixed by #34.
> 
> Can you confirm whether binaries like `rtoml-0.7.1-cp39-cp39-macosx_11_0_arm64.whl` will work for you?

Thank you, I think that fixed the issue on MacOS since I can install it without any other dependencies. 

> Okay, I've looked and you're right, `pyproject.toml` seems to be the only way to do this.
> 
> However I really don't want more configure files than are necessary. I'm therefore happy to accept this if we switch completely from `setup.cfg` to `pyproject.toml`.
> 
> All tools configured via `setup.cfg` can also be configured via `pyproject.toml`, except flake8 which will have to be configured via command line arguments in `Makefile`.
> 
> Are you happy to do this? Otherwise I'll do it when I next get around to it.

To me it sounds like a good idea to migrate from `setup.cfg` to `pyproject.toml`. I can update this pull request sometime soon. Thanks!

**Comment by oittaa** [comment]
Are there any issues with the current pull request that you'd like to resolve?

**Comment by samuelcolvin** [comment]
i think with this we should be able to remove 

https://github.com/samuelcolvin/rtoml/blob/7d68375d0863bb4c1998f7844e11eea7709ac83b/Makefile#L6

??

**Comment by samuelcolvin** [comment]
great, thank you @oittaa. I'll make a new release soon.

**Comment by oittaa** [comment]
Great and thanks for the additional cleanup of the pull request!

**Pull request merged**
